### PR TITLE
74 make fsw flight software

### PR DESCRIPTION
**Pull request by LyonFoster**
## Issue 74

Added some basic structure for the fsw stuff. Not much populated, but slowly we can start getting some of this built out

## Changes

added io, functional, util, config directories

## TODO

- [ ] ...basically everything else

# Request For Feedback
- if you think that any folders or files should be renamed then let me know. Everything else (stubs, the state machine) will be changed eventually

# Future Work
-  Reorganize the FSW if necessary

### CODE REVIEW

**Review by Tim-Behrer — DISMISSED** [review]

**Review by aidanwoodcu — APPROVED** [review]
Might be worth having a group discussion about how we want things to be structured but I don't personally have any strong objections to how this looks right now

**Comment by LyonFoster** [comment]
> Might be worth having a group discussion about how we want things to be structured but I don't personally have any strong objections to how this looks right now

yeah as I push stuff feel free to update this with thoughts and opinions on the structure

**Review by katebenic — APPROVED** [review]
Yeah this structure looks good to me

**Review by Tim-Behrer — APPROVED** [review]
I think this is a good rough draft, allows for the rest of FSW to be built

**Review by katebenic — APPROVED** [review]

**Pull request merged**
