### PR TITLE
110 fsw the full monty

### PR DESCRIPTION
**Pull request by LyonFoster**
Full guidance is working but "go home" is not tested yet because of stuff with the batteries in the sim. But for now this can probably count as "done"

### CODE REVIEW

**Comment by aidanwoodcu** [comment]
Just tried this with the go home code and the behavior is that it just kind of goes diagonally and crashes into the ground. It might make more sense to aim a bit above the ground and then we can just switch to manual/autoland to land it.

**Comment by LyonFoster** [comment]
aimed a meter above the ground

**Review by aidanwoodcu — DISMISSED** [review]

**Comment by LyonFoster** [comment]
I wonder if there's a better way to do this? I agree we should change the mode the drones in, but I wonder if there's a mavros topic that handles this sort of thing? Kinda waypoints it out so that we don't just be line for "home"

**Comment by LyonFoster** [comment]
also is this code messy or hard to read?

**Comment by aidanwoodcu** [comment]
> I wonder if there's a better way to do this? I agree we should change the mode the drones in, but I wonder if there's a mavros topic that handles this sort of thing? Kinda waypoints it out so that we don't just be line for "home"

It looks like PX4/QGroundControl support [a few different configurable battery failsafe modes](https://docs.px4.io/main/en/advanced_config/parameter_reference.html#:~:text=Battery%20failsafe%20mode,at%20emergency%20level) that can be tripped by a [configurable low battery threshold](https://docs.px4.io/main/en/advanced_config/parameter_reference.html#:~:text=Critical%20threshold,will%20trigger%20RTL.). As long as we configure that correctly we might be able to completely remove battery-related stuff from our FSW.

**Comment by LyonFoster** [comment]
Sounds good. Still crashing tho?

**Comment by aidanwoodcu** [comment]
> Sounds good. Still crashing tho?

Your fix that makes it hover a meter above ground does prevent it from crashing. But the built in battery failsafe might be the "better way to do this".

**Comment by LyonFoster** [comment]
Okay let's do that then.

**Comment by aidanwoodcu** [comment]
> Okay let's do that then.

Cool, I'll remove the Go Home state from the state machine and make a PR

**Review by aidanwoodcu — APPROVED** [review]
lgtm

**Review by Tim-Behrer — APPROVED** [review]
lgtm

**Pull request merged**
